[package]
name = "robotalk"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clack-extensions = { version = "0.1.0", features = ["audio-ports", "clack-plugin", "note-ports", "params", "state"] }
clack-plugin = "0.1.0"
misaki-rs = { version = "0.3.0", default-features = false }
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = "s"
lto = true
