#include "trommelsynthesizer.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "samples.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define TAU (2.0 * M_PI)

// Tests set this to render voices at unity so test/render.c can measure them.
int trommelsynthesizer_raw_gain = 0;

// Per-voice output gains, generated by `render --calibrate`.
#include "gains.h"

// ---- primitives ------------------------------------------------------------

typedef struct {
  double ic1, ic2, g, k, a1, a2, a3;
} Svf;

static void svf_set(Svf* s, double fc, double q, double sr) {
  if (fc > sr * 0.45)
    fc = sr * 0.45;
  s->g = tan(M_PI * fc / sr);
  s->k = 1.0 / q;
  s->a1 = 1.0 / (1.0 + s->g * (s->g + s->k));
  s->a2 = s->g * s->a1;
  s->a3 = s->g * s->a2;
}

static void svf_tick(Svf* s, double x, double* lp, double* bp, double* hp) {
  double v3 = x - s->ic2;
  double v1 = s->a1 * s->ic1 + s->a2 * v3;
  double v2 = s->ic2 + s->a2 * s->ic1 + s->a3 * v3;
  s->ic1 = 2 * v1 - s->ic1;
  s->ic2 = 2 * v2 - s->ic2;
  *bp = v1;
  *lp = v2;
  *hp = x - s->k * v1 - v2;
}

static inline double blep(double t, double dt) {
  if (t < dt) {
    t /= dt;
    return t + t - t * t - 1.0;
  }
  if (t > 1.0 - dt) {
    t = (t - 1.0) / dt;
    return t * t + t + t + 1.0;
  }
  return 0.0;
}

static inline double square(double ph, double dt) {
  double s = ph < 0.5 ? 1.0 : -1.0;
  s += blep(ph, dt);
  s -= blep(fmod(ph + 0.5, 1.0), dt);
  return s;
}

static inline double onepole_a(double fc, double sr) { return 1.0 - exp(-TAU * fc / sr); }

// ---- voice configuration ---------------------------------------------------

enum { K_NONE,
       K_SWEPT,
       K_SNARE,
       K_METAL,
       K_PING,
       K_CLAP,
       K_NOISE,
       K_SAMPLE };

typedef struct {
  uint8_t kind;
  float c[10];
} Cfg;

// K_SWEPT  c: f0 Hz, sweep amount, sweep tau, amp tau, click, click lp Hz,
//             drive, noise body, tone->drive (0/1)
// K_SNARE  c: osc1 Hz, osc2 Hz, osc1 tau, osc2 tau, pitch drop, noise hp Hz,
//             noise lp Hz, noise tau, noise level, snap click
// K_METAL  c: freq scale, bp Hz, hp Hz, fast tau, slow tau, slow mix,
//             noise fraction, click
// K_PING   c: f1, f2, tau1, tau2, mix2, bp Hz (0 = none), drive, squares (0/1),
//             tail mix, tail tau
// K_CLAP   c: bp Hz, Q, burst spacing, bursts, burst tau, tail tau, tail level,
//             hp Hz
// K_NOISE  c: hp Hz, attack tau, decay tau
#define SW(f0, amt, ftau, atau, click, clk, drv, nb, td)      \
  {                                                           \
    K_SWEPT, { f0, amt, ftau, atau, click, clk, drv, nb, td } \
  }
#define SN(o1, o2, t1, t2, drop, hp, lp, nt, nl, snap)      \
  {                                                         \
    K_SNARE, { o1, o2, t1, t2, drop, hp, lp, nt, nl, snap } \
  }
#define MT(sc, bp, hp, tf, ts, mix, nz, clk)      \
  {                                               \
    K_METAL, { sc, bp, hp, tf, ts, mix, nz, clk } \
  }
#define PG(f1, f2, t1, t2, m2, bp, drv, sq, tm, tt)     \
  {                                                     \
    K_PING, { f1, f2, t1, t2, m2, bp, drv, sq, tm, tt } \
  }
#define CL(bp, q, sp, n, bt, tt, tl, hp)     \
  {                                          \
    K_CLAP, { bp, q, sp, n, bt, tt, tl, hp } \
  }
#define NZ(hp, atk, dec)      \
  {                           \
    K_NOISE, { hp, atk, dec } \
  }
static const Cfg SAMPLE_CFG = {K_SAMPLE, {0}};

// Constants for the analog machines come from circuit analyses of the real
// hardware (the 808 metallic square cluster, the bridged-T resonators, the
// clap's burst envelope) and were then tuned by ear against the machines'
// characteristic behaviour. See README.md#accuracy.
// clang-format off
static const Cfg CFG[M_COUNT][V_COUNT] = {
    [M_808] = {
        [V_BD] = SW(52, 1.1, 0.010, 0.22, 0.35, 900, 1.4, 0, 0),
        [V_SD] = SN(180, 330, 0.075, 0.040, 0.2, 1800, 7000, 0.060, 1.0, 0.1),
        [V_RS] = PG(455, 1667, 0.008, 0.004, 0.8, 0, 4.0, 0, 0, 0),
        [V_CP] = CL(1000, 2.2, 0.0105, 3, 0.0035, 0.075, 0.9, 400),
        [V_LT] = SW(88, 0.5, 0.012, 0.17, 0.10, 2500, 1.1, 0, 0),
        [V_MT] = SW(131, 0.5, 0.012, 0.13, 0.10, 2500, 1.1, 0, 0),
        [V_HT] = SW(190, 0.5, 0.012, 0.10, 0.10, 2500, 1.1, 0, 0),
        [V_CH] = MT(1.0, 3400, 7000, 0.022, 0.022, 0.0, 0.0, 0.3),
        [V_OH] = MT(1.0, 3400, 7000, 0.040, 0.120, 0.6, 0.0, 0.3),
        [V_CY] = MT(1.0, 3400, 6000, 0.200, 0.600, 0.6, 0.0, 0.3),
        [V_CB] = PG(540, 800, 0.009, 0.009, 1.0, 2640, 1.0, 1, 0.35, 0.12),
        [V_LC] = SW(165, 0.25, 0.008, 0.12, 0.20, 3000, 1.0, 0, 0),
        [V_MC] = SW(250, 0.25, 0.008, 0.10, 0.20, 3000, 1.0, 0, 0),
        [V_HC] = SW(370, 0.25, 0.008, 0.08, 0.20, 3000, 1.0, 0, 0),
        [V_MA] = NZ(5000, 0.0008, 0.018),
        [V_CL] = PG(2450, 1850, 0.012, 0.008, 0.5, 0, 2.5, 0, 0, 0),
    },
    [M_909] = {
        [V_BD] = SW(52, 3.2, 0.011, 0.13, 0.8, 3500, 2.0, 0, 1),
        [V_SD] = SN(185, 330, 0.050, 0.028, 0.35, 1200, 9500, 0.090, 1.1, 0.5),
        [V_RS] = PG(480, 1700, 0.006, 0.004, 0.9, 0, 5.0, 0, 0, 0),
        [V_CP] = CL(1150, 2.4, 0.0095, 3, 0.0030, 0.120, 0.9, 500),
        [V_LT] = SW(100, 1.0, 0.018, 0.18, 0.35, 3000, 1.2, 0, 0),
        [V_MT] = SW(150, 1.0, 0.018, 0.14, 0.35, 3000, 1.2, 0, 0),
        [V_HT] = SW(222, 1.0, 0.018, 0.11, 0.35, 3000, 1.2, 0, 0),
        [V_CH] = MT(1.09, 3600, 7800, 0.028, 0.028, 0.0, 0.5, 0.5),
        [V_OH] = MT(1.09, 3600, 7800, 0.060, 0.140, 0.55, 0.5, 0.5),
        [V_CY] = MT(1.09, 3600, 5500, 0.300, 0.700, 0.55, 0.4, 0.5),
        [V_RD] = MT(0.93, 3600, 5000, 0.400, 0.900, 0.5, 0.3, 0.3),
    },
    // Simmons SDS-V: analog drum module famous for its swept "pew" toms.
    [M_SDSV] = {
        [V_BD] = SW(58, 1.2, 0.020, 0.16, 0.25, 1500, 1.3, 0, 0),
        [V_SD] = SN(210, 340, 0.060, 0.035, 0.6, 1500, 8500, 0.130, 1.2, 0.3),
        [V_CP] = CL(1300, 1.8, 0.012, 3, 0.004, 0.090, 1.1, 600),
        [V_LT] = SW(105, 3.5, 0.035, 0.22, 0.30, 3500, 1.5, 0.15, 0),
        [V_MT] = SW(155, 3.5, 0.035, 0.17, 0.30, 3500, 1.5, 0.15, 0),
        [V_HT] = SW(230, 3.5, 0.035, 0.13, 0.30, 3500, 1.5, 0.15, 0),
        [V_CH] = MT(1.0, 6000, 6000, 0.030, 0.030, 0.0, 0.9, 0.2),
        [V_OH] = MT(1.0, 6000, 6000, 0.080, 0.150, 0.5, 0.9, 0.2),
    },
    // Roland CR-78 (1978): the first programmable machine, a small palette of
    // soft analog voices.
    [M_CR78] = {
        [V_BD] = SW(70, 0.8, 0.012, 0.10, 0.15, 1200, 1.0, 0, 0),
        [V_SD] = SN(190, 290, 0.060, 0.035, 0.1, 1800, 6000, 0.110, 0.9, 0.05),
        [V_RS] = PG(600, 1800, 0.010, 0.005, 0.7, 0, 3.0, 0, 0, 0),
        [V_CH] = MT(0.95, 4500, 5500, 0.040, 0.040, 0.0, 0.3, 0.2),
        [V_OH] = MT(0.95, 4500, 5500, 0.080, 0.150, 0.5, 0.3, 0.2),
        [V_CY] = MT(0.95, 4500, 4500, 0.300, 0.700, 0.5, 0.3, 0.2),
        [V_CB] = PG(560, 845, 0.010, 0.010, 1.0, 2400, 1.0, 1, 0.30, 0.10),
        [V_TB] = NZ(4500, 0.0015, 0.080),
        [V_MA] = NZ(6000, 0.0008, 0.030),
        [V_CL] = PG(2400, 1800, 0.014, 0.009, 0.5, 0, 2.5, 0, 0, 0),
        [V_HC] = SW(480, 0.15, 0.005, 0.08, 0.15, 4000, 1.0, 0, 0),
        [V_MC] = SW(330, 0.15, 0.005, 0.10, 0.15, 4000, 1.0, 0, 0),
    },
};

// clang-format on

// Peak each analog voice is normalised to at default settings, before the
// level knob (default 0.8) and velocity.
static const float TARGET[V_COUNT] = {
    [V_BD] = 0.85,
    [V_BD2] = 0.85,
    [V_SD] = 0.75,
    [V_SD2] = 0.75,
    [V_RS] = 0.6,
    [V_CP] = 0.6,
    [V_LT] = 0.7,
    [V_MT] = 0.7,
    [V_HT] = 0.7,
    [V_CH] = 0.4,
    [V_OH] = 0.45,
    [V_CY] = 0.5,
    [V_RD] = 0.45,
    [V_CB] = 0.5,
    [V_CB2] = 0.5,
    [V_TB] = 0.4,
    [V_LC] = 0.65,
    [V_MC] = 0.65,
    [V_HC] = 0.65,
    [V_TI] = 0.6,
    [V_MA] = 0.35,
    [V_CL] = 0.5,
};

const float* trommelsynthesizer_targets(void) { return TARGET; }

// Analog voices come from CFG; anything else the machine has is a sample.
static const Cfg* cfg_for(int m, int v) {
  if (m < 0 || m >= M_COUNT || v < 0 || v >= V_COUNT)
    return NULL;
  if (CFG[m][v].kind != K_NONE)
    return &CFG[m][v];
  return sample_get(m, v) ? &SAMPLE_CFG : NULL;
}

bool eng_machine_has(int m, int v) { return cfg_for(m, v) != NULL; }

// ---- General MIDI drum map -------------------------------------------------

typedef struct {
  int8_t v, s;
} Cand;
// Voices are stored +1 so a zeroed (unused) slot reads as "none", not V_BD.
#define C(v, s) {V_##v + 1, s}
// Each GM key lists the voices to try, best first, with a semitone offset.
// clang-format off
static const Cand GM[47][4] = {
    [35 - 35] = { C(BD2, 0), C(BD, 0) },
    [36 - 35] = { C(BD, 0) },
    [37 - 35] = { C(RS, 0), C(CL, -5) },
    [38 - 35] = { C(SD, 0) },
    [39 - 35] = { C(CP, 0), C(RS, -3) },
    [40 - 35] = { C(SD2, 0), C(SD, 2) },
    [41 - 35] = { C(LT, -1), C(MT, -6), C(HT, -11) },
    [42 - 35] = { C(CH, 0) },
    [43 - 35] = { C(LT, 2), C(MT, -4), C(HT, -9) },
    [44 - 35] = { C(CH, 0) },
    [45 - 35] = { C(MT, -1), C(LT, 4), C(HT, -7) },
    [46 - 35] = { C(OH, 0) },
    [47 - 35] = { C(MT, 2), C(LT, 7), C(HT, -5) },
    [48 - 35] = { C(HT, -1), C(MT, 5), C(LT, 9) },
    [49 - 35] = { C(CY, 0), C(OH, 3) },
    [50 - 35] = { C(HT, 2), C(MT, 8), C(LT, 12) },
    [51 - 35] = { C(RD, 0), C(CY, 3), C(OH, 2) },
    [52 - 35] = { C(CY, -4), C(OH, -3) },
    [53 - 35] = { C(RD, 4), C(CB, 3), C(CY, 5), C(OH, 5) },
    [54 - 35] = { C(TB, 0), C(MA, 0) },
    [55 - 35] = { C(CY, 4), C(OH, 4) },
    [56 - 35] = { C(CB, 0) },
    [57 - 35] = { C(CY, 2), C(OH, 1) },
    [59 - 35] = { C(RD, 2), C(CY, 1), C(OH, 0) },
    [60 - 35] = { C(HC, 3), C(TI, 3), C(MC, 5) },
    [61 - 35] = { C(MC, 0), C(LC, 4), C(TI, -3) },
    [62 - 35] = { C(HC, 0) },
    [63 - 35] = { C(HC, 0) },
    [64 - 35] = { C(LC, 0), C(MC, -4) },
    [65 - 35] = { C(TI, 0), C(HC, 5) },
    [66 - 35] = { C(TI, -5), C(MC, 0) },
    [67 - 35] = { C(CB, 4) },
    [68 - 35] = { C(CB2, 0), C(CB, -4) },
    [69 - 35] = { C(MA, -2) },
    [70 - 35] = { C(MA, 0) },
    [75 - 35] = { C(CL, 0) },
    [76 - 35] = { C(CL, 3) },
    [77 - 35] = { C(CL, -3) },
};
// clang-format on
#undef C

bool eng_gm_lookup(int m, int key, int* voice, int* semis) {
  if (key < 35 || key > 81)
    return false;
  const Cand* c = GM[key - 35];
  for (int i = 0; i < 4 && c[i].v; i++) {
    if (eng_machine_has(m, c[i].v - 1)) {
      *voice = c[i].v - 1;
      *semis = c[i].s;
      return true;
    }
  }
  return false;
}

// ---- engine ----------------------------------------------------------------

typedef struct {
  bool active;
  int machine, voice;
  const Cfg* cfg;
  double t, dt, sr;
  double gain, vel;
  double choke;  // >0: ramping out, seconds left
  float p[P_COUNT];
  // working constants, set at trigger
  double f0, famt, ftau, atau, click, drive, nbody;
  double ph[6], fr[6];
  double aux[8];
  Svf s1, s2, s3;
  double lp1, lp2, ca;
  uint32_t rng;
  // samples
  const Sample* smp;
  double pos, step;
  double tone_lp, tone_a;
} Voice;

struct Engine {
  double sr;
  int machine;
  float master;
  float vp[V_COUNT][P_COUNT];
  Voice voices[V_COUNT];
};

static inline double rnd(Voice* v) {
  v->rng ^= v->rng << 13;
  v->rng ^= v->rng >> 17;
  v->rng ^= v->rng << 5;
  return (double)(int32_t)v->rng / 2147483648.0;
}

static inline double decay_scale(double d) { return pow(2.0, (d - 0.5) * 3.0); }
static inline double tone_scale(double t, double range) { return pow(2.0, (t - 0.5) * range); }

static const double METAL[6] = {205.3, 304.4, 369.6, 522.7, 540.0, 800.0};

static void voice_init(Voice* v, int semis) {
  const Cfg* c = v->cfg;
  const float* p = v->p;
  double tr = pow(2.0, (p[P_TUNE] + semis) / 12.0);
  double ds = decay_scale(p[P_DECAY]);
  double tn = p[P_TONE];
  double ex = p[P_EXTRA];
  v->t = 0;
  v->rng = 0x9E3779B9u ^ (uint32_t)(v->voice * 2654435761u);
  v->lp1 = v->lp2 = 0;
  memset(v->ph, 0, sizeof v->ph);
  memset(&v->s1, 0, sizeof v->s1);
  memset(&v->s2, 0, sizeof v->s2);
  memset(&v->s3, 0, sizeof v->s3);
  switch (c->kind) {
    case K_SWEPT:
      v->f0 = c->c[0] * tr;
      v->famt = c->c[1];
      v->ftau = c->c[2];
      v->atau = c->c[3] * ds;
      v->click = c->c[4] * 2.0 * ex * (c->c[8] > 0 ? 1.0 : 2.0 * tn);
      v->ca = onepole_a(c->c[5] * (c->c[8] > 0 ? 1.0 : tone_scale(tn, 3.0)), v->sr);
      v->drive = c->c[6] * (c->c[8] > 0 ? 0.4 + 1.2 * tn : 1.0);
      v->nbody = c->c[7];
      break;
    case K_SNARE:
      v->aux[0] = c->c[0] * tr;
      v->aux[1] = c->c[1] * tr;
      v->aux[2] = c->c[2] * ds;
      v->aux[3] = c->c[3] * ds;
      v->aux[4] = c->c[7] * ds * (0.6 + 0.8 * ex);
      v->aux[5] = c->c[8] * (0.3 + 1.4 * ex);
      v->aux[6] = 0.5 + tn;  // osc2 balance
      svf_set(&v->s1, c->c[5], 0.7, v->sr);
      v->ca = onepole_a(c->c[6] * tone_scale(tn, 2.0), v->sr);
      break;
    case K_METAL:
      for (int i = 0; i < 6; i++) v->fr[i] = METAL[i] * c->c[0] * tr;
      svf_set(&v->s1, c->c[1] * tr, 1.2, v->sr);
      svf_set(&v->s2, c->c[2] * tone_scale(tn, 1.2), 0.7, v->sr);
      v->aux[0] = c->c[3] * ds;
      v->aux[1] = c->c[4] * ds;
      v->aux[2] = fmin(1.0, fmax(0.0, c->c[5] * (0.4 + 1.2 * tn)));
      break;
    case K_PING:
      v->aux[0] = c->c[0] * tr;
      v->aux[1] = c->c[1] * tr;
      v->aux[2] = c->c[2] * ds;
      v->aux[3] = c->c[3] * ds;
      v->aux[4] = c->c[4] * (0.4 + 1.2 * tn);
      v->aux[5] = c->c[9] * ds;
      if (c->c[5] > 0)
        svf_set(&v->s1, c->c[5] * tr, 1.5, v->sr);
      break;
    case K_CLAP:
      svf_set(&v->s1, c->c[0] * tone_scale(tn, 1.0), c->c[1], v->sr);
      svf_set(&v->s2, c->c[7], 0.7, v->sr);
      v->aux[0] = c->c[5] * ds;
      break;
    case K_NOISE:
      svf_set(&v->s1, c->c[0] * tone_scale(tn, 1.0), 0.7, v->sr);
      v->aux[0] = c->c[2] * ds;
      break;
    default:
      break;
  }
}

static void sample_init(Voice* v, int semis) {
  v->smp = sample_get(v->machine, v->voice);
  v->pos = 0;
  double tr = pow(2.0, (v->p[P_TUNE] + semis) / 12.0);
  v->step = (double)v->smp->rate / v->sr * tr;
  double d = v->p[P_DECAY];
  v->aux[0] = d >= 0.5 ? 0.0 : 0.02 * pow(40.0, d * 2.0);  // decay tau, 0 = off
  v->tone_lp = 0;
  double t = v->p[P_TONE];
  v->aux[1] = t < 0.5 ? onepole_a(400.0 * pow(50.0, t * 2.0), v->sr) : 0.0;
  v->aux[2] = t > 0.5 ? (t - 0.5) * 2.0 * 1.0 : 0.0;  // shelf boost amount
  v->tone_a = onepole_a(3000.0, v->sr);
}

static inline double smp_at(const Sample* s, int64_t i) {
  if (i < 0 || (uint32_t)i >= s->frames)
    return 0.0;
  return (int16_t)(s->data[2 * i] | (s->data[2 * i + 1] << 8)) / 32768.0;
}

static double tick_sample(Voice* v) {
  const Sample* s = v->smp;
  int64_t i = (int64_t)v->pos;
  double f = v->pos - (double)i;
  double a = smp_at(s, i - 1), b = smp_at(s, i), c = smp_at(s, i + 1), d = smp_at(s, i + 2);
  double x = b + 0.5 * f * (c - a + f * (2 * a - 5 * b + 4 * c - d + f * (3 * (b - c) + d - a)));
  v->pos += v->step;
  if (v->pos >= s->frames)
    v->active = false;
  if (v->aux[0] > 0)
    x *= exp(-v->t / v->aux[0]);
  if (v->aux[1] > 0) {
    v->tone_lp += v->aux[1] * (x - v->tone_lp);
    x = v->tone_lp;
  } else if (v->aux[2] > 0) {
    v->lp2 += v->tone_a * (x - v->lp2);
    x += (x - v->lp2) * v->aux[2];
  }
  return x;
}

static double tick_swept(Voice* v) {
  double t = v->t;
  double f = v->f0 * (1.0 + v->famt * exp(-t / v->ftau));
  v->ph[0] += f / v->sr;
  v->ph[0] -= floor(v->ph[0]);
  double e = exp(-t / v->atau);
  double x = sin(TAU * v->ph[0]) * e;
  double n = rnd(v);
  v->lp1 += v->ca * (n - v->lp1);
  x += v->lp1 * exp(-t / 0.0015) * v->click;
  if (v->nbody > 0) {
    v->lp2 += 0.2 * (n - v->lp2);
    x += v->lp2 * e * e * v->nbody;
  }
  if (t > 0.01 && e < 0.0005)
    v->active = false;
  return tanh(v->drive * x) / tanh(v->drive);
}

static double tick_snare(Voice* v) {
  double t = v->t, dt = 1.0 / v->sr;
  const double* a = v->aux;
  double drop = v->cfg->c[4];
  double f1 = a[0] * (1.0 + drop * exp(-t / 0.015));
  double f2 = a[1] * (1.0 + drop * exp(-t / 0.015));
  v->ph[0] += f1 * dt;
  v->ph[1] += f2 * dt;
  v->ph[0] -= floor(v->ph[0]);
  v->ph[1] -= floor(v->ph[1]);
  double e1 = exp(-t / a[2]), e2 = exp(-t / a[3]);
  double body = sin(TAU * v->ph[0]) * e1 * 0.75 + sin(TAU * v->ph[1]) * e2 * 0.5 * a[6];
  double n = rnd(v), lp, bp, hp;
  svf_tick(&v->s1, n, &lp, &bp, &hp);
  v->lp1 += v->ca * (hp - v->lp1);
  double ne = exp(-t / a[4]);
  double x = body * 0.6 + v->lp1 * ne * a[5] * 0.5;
  x += rnd(v) * exp(-t / 0.0007) * v->cfg->c[9];
  if (t > 0.02 && e1 < 0.0005 && e2 < 0.0005 && ne < 0.0005)
    v->active = false;
  return x;
}

static double tick_metal(Voice* v) {
  double t = v->t, dt = 1.0 / v->sr;
  double s = 0;
  for (int i = 0; i < 6; i++) {
    v->ph[i] += v->fr[i] * dt;
    v->ph[i] -= floor(v->ph[i]);
    s += square(v->ph[i], v->fr[i] * dt);
  }
  s /= 3.0;
  double nf = v->cfg->c[6];
  double x = s * (1.0 - nf) + rnd(v) * nf * 0.8;
  double lp, bp, hp, lp2, bp2, hp2;
  svf_tick(&v->s1, x, &lp, &bp, &hp);
  svf_tick(&v->s2, bp * 1.5 + x * 0.3, &lp2, &bp2, &hp2);
  double e = (1.0 - v->aux[2]) * exp(-t / v->aux[0]) + v->aux[2] * exp(-t / v->aux[1]);
  double click = rnd(v) * exp(-t / 0.0008) * v->cfg->c[7];
  if (t > 0.01 && e < 0.0003)
    v->active = false;
  return (hp2 + click * 0.5) * e;
}

static double tick_ping(Voice* v) {
  double t = v->t, dt = 1.0 / v->sr;
  const double* a = v->aux;
  bool sq = v->cfg->c[7] > 0;
  v->ph[0] += a[0] * dt;
  v->ph[1] += a[1] * dt;
  v->ph[0] -= floor(v->ph[0]);
  v->ph[1] -= floor(v->ph[1]);
  double x, e;
  if (sq) {
    x = square(v->ph[0], a[0] * dt) + square(v->ph[1], a[1] * dt) * a[4];
    double tm = v->cfg->c[8];
    e = (1.0 - tm) * exp(-t / a[2]) + tm * exp(-t / a[5]);
    double lp, bp, hp;
    svf_tick(&v->s1, x, &lp, &bp, &hp);
    x = bp * e;
  } else {
    double e1 = exp(-t / a[2]), e2 = exp(-t / a[3]);
    x = sin(TAU * v->ph[0]) * e1 + sin(TAU * v->ph[1]) * a[4] * e2;
    double dr = v->cfg->c[6];
    x = tanh(dr * x) / tanh(dr);
    e = fmax(e1, e2);
  }
  if (t > 0.005 && e < 0.0005)
    v->active = false;
  return x;
}

static double tick_clap(Voice* v) {
  double t = v->t;
  const Cfg* c = v->cfg;
  double sp = c->c[2], nb = c->c[3], bt = c->c[4], tl = c->c[6];
  double e;
  if (t < nb * sp) {
    e = exp(-fmod(t, sp) / bt);
  } else {
    double tt = t - nb * sp;
    e = exp(-tt / bt) + tl * exp(-tt / v->aux[0]);
  }
  double n = rnd(v), lp, bp, hp, lp2, bp2, hp2;
  svf_tick(&v->s1, n, &lp, &bp, &hp);
  svf_tick(&v->s2, bp, &lp2, &bp2, &hp2);
  if (t > nb * sp + 0.01 && e < 0.0005)
    v->active = false;
  return hp2 * e;
}

static double tick_noise(Voice* v) {
  double t = v->t;
  double n = rnd(v), lp, bp, hp;
  svf_tick(&v->s1, n, &lp, &bp, &hp);
  double e = (1.0 - exp(-t / v->cfg->c[1])) * exp(-t / v->aux[0]);
  if (t > 0.005 && e < 0.0005)
    v->active = false;
  return hp * e;
}

static double voice_tick(Voice* v) {
  double x = 0;
  switch (v->cfg->kind) {
    case K_SWEPT:
      x = tick_swept(v);
      break;
    case K_SNARE:
      x = tick_snare(v);
      break;
    case K_METAL:
      x = tick_metal(v);
      break;
    case K_PING:
      x = tick_ping(v);
      break;
    case K_CLAP:
      x = tick_clap(v);
      break;
    case K_NOISE:
      x = tick_noise(v);
      break;
    case K_SAMPLE:
      x = tick_sample(v);
      break;
    default:
      v->active = false;
  }
  v->t += v->dt;
  if (v->choke > 0) {
    x *= v->choke / 0.004;
    v->choke -= v->dt;
    if (v->choke <= 0)
      v->active = false;
  }
  return x * v->gain;
}

Engine* eng_create(double sr) {
  Engine* e = calloc(1, sizeof *e);
  e->sr = sr > 0 ? sr : 48000.0;
  e->master = 1.0f;
  for (int v = 0; v < V_COUNT; v++) {
    e->vp[v][P_LEVEL] = 0.8f;
    e->vp[v][P_TUNE] = 0.0f;
    e->vp[v][P_DECAY] = 0.5f;
    e->vp[v][P_TONE] = 0.5f;
    e->vp[v][P_EXTRA] = 0.5f;
  }
  return e;
}

void eng_destroy(Engine* e) { free(e); }

void eng_reset(Engine* e) {
  for (int v = 0; v < V_COUNT; v++) e->voices[v].active = false;
}

void eng_trigger(Engine* e, int machine, int voice, int semis, float vel) {
  if (!eng_machine_has(machine, voice))
    return;
  Voice* v = &e->voices[voice];
  memset(v, 0, sizeof *v);
  v->machine = machine;
  v->voice = voice;
  v->cfg = cfg_for(machine, voice);
  v->sr = e->sr;
  v->dt = 1.0 / e->sr;
  memcpy(v->p, e->vp[voice], sizeof v->p);
  v->vel = vel;
  double k = 1.0;
  if (!trommelsynthesizer_raw_gain)
    k = K_GAIN[machine][voice];
  v->gain = e->master * v->p[P_LEVEL] * vel * k;
  if (v->cfg->kind == K_SAMPLE)
    sample_init(v, semis);
  else
    voice_init(v, semis);
  v->active = true;
  // Closed hat chokes the open hat, as on the real machines.
  if (voice == V_CH && e->voices[V_OH].active && e->voices[V_OH].choke <= 0)
    e->voices[V_OH].choke = 0.004;
}

void eng_note_on(Engine* e, int key, float vel) {
  int v, s;
  if (eng_gm_lookup(e->machine, key, &v, &s))
    eng_trigger(e, e->machine, v, s, vel);
}

static inline float softclip(float x) {
  float a = fabsf(x);
  if (a <= 0.8f)
    return x;
  float y = 0.8f + 0.2f * tanhf((a - 0.8f) / 0.2f);
  return x < 0 ? -y : y;
}

void eng_render(Engine* e, float* l, float* r, uint32_t n) {
  for (uint32_t i = 0; i < n; i++) {
    double sum = 0;
    for (int v = 0; v < V_COUNT; v++) {
      if (e->voices[v].active)
        sum += voice_tick(&e->voices[v]);
    }
    float y = trommelsynthesizer_raw_gain ? (float)sum : softclip((float)sum);
    l[i] = r[i] = y;
  }
}

// ---- params ----------------------------------------------------------------

void eng_set_param(Engine* e, uint32_t id, double value) {
  if (id == PID_MACHINE) {
    int m = (int)(value + 0.5);
    e->machine = m < 0 ? 0 : (m >= M_COUNT ? M_COUNT - 1 : m);
  } else if (id == PID_MASTER) {
    e->master = (float)value;
  } else if (id < PID_COUNT) {
    uint32_t k = id - 2;
    e->vp[k / P_COUNT][k % P_COUNT] = (float)value;
  }
}

double eng_get_param(const Engine* e, uint32_t id) {
  if (id == PID_MACHINE)
    return e->machine;
  if (id == PID_MASTER)
    return e->master;
  if (id < PID_COUNT) {
    uint32_t k = id - 2;
    return e->vp[k / P_COUNT][k % P_COUNT];
  }
  return 0;
}

static const char* const VOICE_ABBR[V_COUNT] = {"BD", "BD2", "SD", "SD2", "RS", "CP", "LT", "MT", "HT", "CH", "OH",
                                                "CY", "RD", "CB", "CB2", "TB", "LC", "MC", "HC", "TI", "MA", "CL"};
static const char* const VOICE_FULL[V_COUNT] = {
    "Bass Drum", "Bass Drum 2", "Snare", "Snare 2", "Rim Shot", "Hand Clap", "Low Tom", "Mid Tom", "High Tom",
    "Closed Hat", "Open Hat", "Crash", "Ride", "Cowbell", "Cowbell Low", "Tambourine", "Low Conga", "Mid Conga",
    "High Conga", "Timbale", "Maracas", "Claves"};
static const char* const PARAM_NAME[P_COUNT] = {"Level", "Tune", "Decay", "Tone", "Extra"};

#define L (1 << P_LEVEL)
#define T (1 << P_TUNE)
#define D (1 << P_DECAY)
#define N (1 << P_TONE)
#define X (1 << P_EXTRA)
// Which knobs each voice exposes (the ones its original had, plus Tone).
// clang-format off
static const uint8_t MASK[V_COUNT] = {
    [V_BD] = L | T | D | N | X, [V_BD2] = L | T | D | N,     [V_SD] = L | T | D | N | X,
    [V_SD2] = L | T | D | N | X, [V_RS] = L | T | N,         [V_CP] = L | D | N,
    [V_LT] = L | T | D | N,     [V_MT] = L | T | D | N,      [V_HT] = L | T | D | N,
    [V_CH] = L | T | D | N,     [V_OH] = L | T | D | N,      [V_CY] = L | T | D | N,
    [V_RD] = L | T | D | N,     [V_CB] = L | T | D | N,      [V_CB2] = L | T | D | N,
    [V_TB] = L | T | D | N,     [V_LC] = L | T | D | N,      [V_MC] = L | T | D | N,
    [V_HC] = L | T | D | N,     [V_TI] = L | T | D | N,      [V_MA] = L | D | N,
    [V_CL] = L | T | N,
};
// clang-format on
#undef L
#undef T
#undef D
#undef N
#undef X

const char* machine_name(int m) {
  static const char* const names[M_COUNT] = {
      [M_808] = "TR-808",
      [M_909] = "TR-909",
      [M_707] = "TR-707",
      [M_505] = "TR-505",
      [M_SDSV] = "SDS-V",
      [M_CR78] = "CR-78",
      [M_LINNDRUM] = "LinnDrum",
      [M_LM1] = "LM-1",
      [M_DMX] = "DMX",
      [M_DRUMULATOR] = "Drumulator",
      [M_DRUMTRAKS] = "Drumtraks",
      [M_MPC60] = "MPC60",
      [M_RX5] = "RX5",
      [M_RZ1] = "RZ-1",
      [M_SK1] = "SK-1",
      [M_KPR77] = "KPR-77",
      [M_DR55] = "DR-55",
      [M_DR110] = "DR-110",
      [M_TR606] = "TR-606",
      [M_RHYTHMACE] = "Rhythm Ace",
      [M_SPACEDRUM] = "Space Drum",
      [M_HR16] = "HR-16",
      [M_SDS5] = "SDS5",
  };
  return m >= 0 && m < M_COUNT ? names[m] : "?";
}

static void fill_info(uint32_t id, ParamInfo* o) {
  memset(o, 0, sizeof *o);
  o->id = id;
  if (id == PID_MACHINE) {
    snprintf(o->name, sizeof o->name, "Machine");
    snprintf(o->module, sizeof o->module, "Global");
    o->max = M_COUNT - 1;
    o->stepped = true;
    return;
  }
  if (id == PID_MASTER) {
    snprintf(o->name, sizeof o->name, "Master");
    snprintf(o->module, sizeof o->module, "Global");
    o->max = 1;
    o->def = 1.0;
    return;
  }
  uint32_t k = id - 2;
  int v = (int)(k / P_COUNT), p = (int)(k % P_COUNT);
  const char* pn = PARAM_NAME[p];
  if (p == P_EXTRA)
    pn = (v == V_BD) ? "Attack" : "Snappy";
  snprintf(o->name, sizeof o->name, "%s %s", VOICE_ABBR[v], pn);
  snprintf(o->module, sizeof o->module, "%s", VOICE_FULL[v]);
  o->min = p == P_TUNE ? -12 : 0;
  o->max = p == P_TUNE ? 12 : 1;
  o->def = p == P_LEVEL ? 0.8 : (p == P_TUNE ? 0.0 : 0.5);
}

uint32_t param_count(void) {
  uint32_t n = 2;
  for (int v = 0; v < V_COUNT; v++)
    for (int p = 0; p < P_COUNT; p++) n += (MASK[v] >> p) & 1;
  return n;
}

bool param_info(uint32_t index, ParamInfo* out) {
  if (index == 0) {
    fill_info(PID_MACHINE, out);
    return true;
  }
  if (index == 1) {
    fill_info(PID_MASTER, out);
    return true;
  }
  uint32_t n = 2;
  for (int v = 0; v < V_COUNT; v++)
    for (int p = 0; p < P_COUNT; p++)
      if ((MASK[v] >> p) & 1) {
        if (n++ == index) {
          fill_info(PID_VOICE(v, p), out);
          return true;
        }
      }
  return false;
}

bool param_info_by_id(uint32_t id, ParamInfo* out) {
  if (id >= PID_COUNT)
    return false;
  if (id >= 2) {
    uint32_t k = id - 2;
    if (!((MASK[k / P_COUNT] >> (k % P_COUNT)) & 1))
      return false;
  }
  fill_info(id, out);
  return true;
}

void param_text(uint32_t id, double value, char* out, uint32_t size) {
  if (id == PID_MACHINE) {
    snprintf(out, size, "%s", machine_name((int)(value + 0.5)));
  } else if (id >= 2 && (id - 2) % P_COUNT == P_TUNE) {
    snprintf(out, size, "%+.1f st", value);
  } else {
    snprintf(out, size, "%d%%", (int)(value * 100.0 + 0.5));
  }
}
