// Generated by scripts/syx2presets.mjs — do not edit.
// 33 DX7 cartridges, 1056 voices, raw 4104-byte bulk-dump SysEx.
#pragma once

#include <stdint.h>

#define DEXED_CART_COUNT 33
#define DEXED_SYSEX_SIZE 4104
// 32 packed voices per cartridge, 128 bytes each, at offset 6.
#define DEXED_VOICES_PER_CART 32

extern const char* const dexed_cart_names[DEXED_CART_COUNT];
extern const uint8_t dexed_cart_data[DEXED_CART_COUNT][DEXED_SYSEX_SIZE];
