#!/usr/bin/env python3
"""Turn a PNG into a C header holding its bytes, so it can be decoded at
runtime with raylib's LoadImageFromMemory and ship inside the binary (no
asset files to install, and the web build gets it for free).

  ./scripts/embed_png.py art/controller.png src/controller_png.h CONTROLLER_PNG
"""
import sys
from pathlib import Path

def main():
  if len(sys.argv) != 4:
    sys.exit(f"usage: {sys.argv[0]} IN.png OUT.h SYMBOL")
  src, out, sym = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
  data = src.read_bytes()
  lines = [
    "// Generated by scripts/embed_png.py — do not edit.",
    f"// source: {src.as_posix()} ({len(data)} bytes)",
    "#pragma once",
    "// clang-format off",
    "",
    f"static const unsigned char {sym}[] = {{",
  ]
  for i in range(0, len(data), 16):
    lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 16]))
  lines += ["};", f"static const int {sym}_LEN = (int)sizeof({sym});", "// clang-format on", ""]
  out.write_text("\n".join(lines))
  print(f"{out} <- {src} ({len(data)} bytes)")

main()
