// Native test harness: renders every voice of every machine.
//
//   render --calibrate   print src/gains.h (per-voice output gains)
//   render --wav DIR     write DIR/<machine>_<voice>.wav and print stats
//   render --check       sanity-check every voice and the GM map (exit 1 on failure)
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../src/trommelsynthesizer.h"

extern int trommelsynthesizer_raw_gain;
extern const float* trommelsynthesizer_targets(void);

// Overall trim so the voices sit with the other instruments in a song.
#define LEVEL 0.8
#define SR 48000
#define FRAMES (SR * 4)

static const char* const VN[V_COUNT] = {"bd", "bd2", "sd", "sd2", "rs", "cp", "lt", "mt", "ht", "ch", "oh",
                                        "cy", "rd", "cb", "cb2", "tb", "lc", "mc", "hc", "ti", "ma", "cl"};

static float* render_voice(int m, int v) {
  Engine* e = eng_create(SR);
  eng_set_param(e, PID_MASTER, 1.0);
  eng_set_param(e, PID_VOICE(v, P_LEVEL), 1.0);
  eng_trigger(e, m, v, 0, 1.0f);
  float* l = calloc(FRAMES, sizeof(float));
  float* r = calloc(FRAMES, sizeof(float));
  eng_render(e, l, r, FRAMES);
  free(r);
  eng_destroy(e);
  return l;
}

static double peak_of(const float* x) {
  double p = 0;
  for (int i = 0; i < FRAMES; i++) p = fmax(p, fabs(x[i]));
  return p;
}

static void write_wav(const char* path, const float* x) {
  FILE* f = fopen(path, "wb");
  uint32_t n = FRAMES * 2, rate = SR, br = SR * 2;
  uint16_t fmt = 1, ch = 1, ba = 2, bits = 16;
  uint32_t sixteen = 16, riff = 36 + n;
  fwrite("RIFF", 1, 4, f);
  fwrite(&riff, 4, 1, f);
  fwrite("WAVEfmt ", 1, 8, f);
  fwrite(&sixteen, 4, 1, f);
  fwrite(&fmt, 2, 1, f);
  fwrite(&ch, 2, 1, f);
  fwrite(&rate, 4, 1, f);
  fwrite(&br, 4, 1, f);
  fwrite(&ba, 2, 1, f);
  fwrite(&bits, 2, 1, f);
  fwrite("data", 1, 4, f);
  fwrite(&n, 4, 1, f);
  for (int i = 0; i < FRAMES; i++) {
    float c = fmaxf(-1, fminf(1, x[i]));
    int16_t s = (int16_t)lrintf(c * 32767);
    fwrite(&s, 2, 1, f);
  }
  fclose(f);
}

int main(int argc, char** argv) {
  const float* target = trommelsynthesizer_targets();
  if (argc >= 2 && strcmp(argv[1], "--calibrate") == 0) {
    trommelsynthesizer_raw_gain = 1;
    float gain[M_COUNT][V_COUNT] = {{0}};
    for (int m = 0; m < M_COUNT; m++) {
      for (int v = 0; v < V_COUNT; v++) {
        if (!eng_machine_has(m, v))
          continue;
        float* x = render_voice(m, v);
        gain[m][v] = (float)(LEVEL * target[v] / peak_of(x));
        free(x);
      }
    }
    printf("// Generated by `render --calibrate`. Do not edit.\n");
    printf("static const float K_GAIN[M_COUNT][V_COUNT] = {\n");
    for (int m = 0; m < M_COUNT; m++) {
      printf("    {");
      for (int v = 0; v < V_COUNT; v++) printf("%s%.4ff", v ? ", " : "", gain[m][v] ? gain[m][v] : 1.0f);
      printf("},\n");
    }
    printf("};\n");
    return 0;
  }
  if (argc >= 3 && strcmp(argv[1], "--wav") == 0) {
    for (int m = 0; m < M_COUNT; m++) {
      for (int v = 0; v < V_COUNT; v++) {
        if (!eng_machine_has(m, v))
          continue;
        float* x = render_voice(m, v);
        char path[512];
        snprintf(path, sizeof path, "%s/%s_%s.wav", argv[2], machine_name(m), VN[v]);
        write_wav(path, x);
        double pk = peak_of(x);
        int last = 0;
        for (int i = 0; i < FRAMES; i++)
          if (fabs(x[i]) > pk * 0.001)
            last = i;
        printf("%-7s %-3s peak %.3f  len(-60dB) %.3fs\n", machine_name(m), VN[v], pk, last / (double)SR);
        free(x);
      }
    }
    return 0;
  }
  if (argc >= 2 && strcmp(argv[1], "--check") == 0) {
    int bad = 0;
    for (int m = 0; m < M_COUNT; m++) {
      for (int v = 0; v < V_COUNT; v++) {
        if (!eng_machine_has(m, v))
          continue;
        float* x = render_voice(m, v);
        double pk = peak_of(x), tail = 0;
        bool finite = true;
        for (int i = 0; i < FRAMES; i++) finite = finite && isfinite(x[i]);
        for (int i = FRAMES - SR / 10; i < FRAMES; i++) tail = fmax(tail, fabs(x[i]));
        // audible, finite, and not still ringing 3.9s after the hit
        if (!finite || pk < 0.05 || pk > 1.0 || tail > 0.01) {
          printf("FAIL %s %s: peak %.3f tail %.4f finite %d\n", machine_name(m), VN[v], pk, tail, finite);
          bad++;
        }
        free(x);
      }
      // every GM key must resolve to a voice the machine really has
      for (int k = 35; k <= 81; k++) {
        int v, s;
        if (eng_gm_lookup(m, k, &v, &s) && !eng_machine_has(m, v)) {
          printf("FAIL %s key %d maps to missing voice %d\n", machine_name(m), k, v);
          bad++;
        }
      }
    }
    printf(bad ? "%d failures\n" : "all voices ok\n", bad);
    return bad ? 1 : 0;
  }
  fprintf(stderr, "usage: render --calibrate | --wav DIR | --check\n");
  return 1;
}
