#!/usr/bin/env node
// syx2presets.mjs — turn DX7 SysEx cartridge files into the inline preset
// table plugins/dexed compiles in (src/presets-data.{h,cpp}).
//
//   node scripts/syx2presets.mjs vendor/syx/*.syx > src/presets-data.cpp
//
// Or, to regenerate both the table and its header:
//
//   node scripts/syx2presets.mjs --out src/presets-data vendor/syx/*.syx
//
// The checked-in table was generated from the 33 banks dexed itself ships
// (`assets/builtin_pgm.zip` upstream — `Dexed_01.syx` plus 32 SynprezFM
// banks), extracted into vendor/syx/ — see README.md#presets.
//
// A WCLAP plugin has no filesystem to read cartridges from at runtime, so
// the raw 4104-byte voice-dump SysEx has to be baked into the wasm's data
// section. Nothing is decoded here: the plugin runs dexed's own cartridge
// loader and voice unpacker over these exact bytes, so the table is a
// faithful copy of what Dexed loads, and a checksum-valid bank is copied
// verbatim.
//
// Every input file must be a DX7 32-voice bulk dump in the one shape Yamaha
// hardware (and every bank in the wild) uses:
//
//   F0 43 0n 09 20 00 <4096 bytes> <checksum> F7     = 4104 bytes total
//
// where the checksum is (-sum(voice bytes)) & 0x7F. Anything else is
// rejected rather than silently normalized — dexed's own loader tolerates
// off-shape streams by copying the first 4096 bytes, which is right for a
// live MIDI stream but wrong for a build-time table.
import { readFileSync, writeFileSync } from "node:fs"
import { basename } from "node:path"

const SYSEX_SIZE = 4104
const HEADER = [0xf0, 0x43, 0x00, 0x09, 0x20, 0x00]

function fail(msg) {
  console.error(`syx2presets: ${msg}`)
  process.exit(1)
}

function checksum(bytes) {
  let sum = 0
  for (let i = 0; i < bytes.length; i++) sum -= bytes[i]
  return sum & 0x7f
}

// Name as dexed's Cartridge::normalizePgmName() renders it: strip the
// don't-care high bit, translate the three special glyphs Yamaha used, and
// blank anything unprintable. Emitted here purely so the table can be read
// and diffed without running the plugin.
function voiceName(raw, offset) {
  let out = ""
  for (let i = 0; i < 10; i++) {
    let c = raw[offset + 118 + i] & 0x7f
    if (c === 92) c = 0x59 // yen -> Y
    else if (c === 126) c = 0x3e // >> -> >
    else if (c === 127) c = 0x3c // << -> <
    else if (c < 32 || c > 127) c = 32
    out += String.fromCharCode(c)
  }
  return out.replace(/\s+$/, "")
}

function loadCart(path) {
  const bytes = readFileSync(path)
  if (bytes.length !== SYSEX_SIZE)
    fail(`${path}: ${bytes.length} bytes, expected ${SYSEX_SIZE} (a DX7 32-voice bulk dump)`)
  // Byte 2 is 0n: sub-status 0 (bulk voice dump) with the channel in the low
  // nibble, so the exact channel doesn't matter — all 16 are the same dump.
  const headerOk =
    bytes[0] === HEADER[0] && bytes[1] === HEADER[1] && bytes[2] >> 4 === 0x00 && bytes[3] === HEADER[3] && bytes[4] === HEADER[4] && bytes[5] === HEADER[5]
  if (!headerOk)
    fail(
      `${path}: header is ${Array.from(bytes.subarray(0, 6), (b) => b.toString(16).padStart(2, "0")).join(" ")}, not a DX7 bulk voice dump (F0 43 0n 09 20 00)`,
    )
  if (bytes[SYSEX_SIZE - 1] !== 0xf7) fail(`${path}: missing 0xF7 terminator`)
  const want = checksum(bytes.subarray(6, 4102))
  if (bytes[4102] !== want)
    fail(`${path}: checksum 0x${bytes[4102].toString(16)}, computed 0x${want.toString(16)}`)

  const voices = []
  for (let i = 0; i < 32; i++) voices.push(voiceName(bytes, 6 + i * 128))
  return { bytes, voices }
}

function hexTable(name, carts) {
  const lines = [`const uint8_t ${name}[DEXED_CART_COUNT][DEXED_SYSEX_SIZE] = {`]
  for (const cart of carts) {
    lines.push(`    {`)
    for (let i = 0; i < cart.bytes.length; i += 16) {
      const row = Array.from(cart.bytes.subarray(i, i + 16), (b) => `0x${b.toString(16).padStart(2, "0")}`)
      lines.push(`        ${row.join(", ")},`)
    }
    lines.push(`    },`)
  }
  lines.push(`};`)
  return lines.join("\n")
}

const args = process.argv.slice(2)
let outBase = null
const files = []
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--out") outBase = args[++i]
  else files.push(args[i])
}
if (files.length === 0) fail("usage: syx2presets.mjs [--out <base>] <bank.syx> [bank2.syx ...]")

const carts = files.map((f) => ({ path: f, name: basename(f, ".syx"), ...loadCart(f) }))

const header = `// Generated by scripts/syx2presets.mjs — do not edit.
// ${carts.length} DX7 cartridges, ${carts.length * 32} voices, raw 4104-byte bulk-dump SysEx.
#pragma once

#include <stdint.h>

#define DEXED_CART_COUNT ${carts.length}
#define DEXED_SYSEX_SIZE ${SYSEX_SIZE}
// 32 packed voices per cartridge, 128 bytes each, at offset 6.
#define DEXED_VOICES_PER_CART 32

extern const char* const dexed_cart_names[DEXED_CART_COUNT];
extern const uint8_t dexed_cart_data[DEXED_CART_COUNT][DEXED_SYSEX_SIZE];
`

const source = `// Generated by scripts/syx2presets.mjs — do not edit.
// See README.md#presets for the banks this was built from, and licensing.
#include "presets-data.h"

const char* const dexed_cart_names[DEXED_CART_COUNT] = {
${carts.map((c) => `    "${c.name}",`).join("\n")}
};

${hexTable("dexed_cart_data", carts)}
`

if (outBase) {
  writeFileSync(`${outBase}.h`, header)
  writeFileSync(`${outBase}.cpp`, source)
  console.error(`syx2presets: wrote ${outBase}.h and ${outBase}.cpp (${carts.length} cartridges, ${carts.length * 32} voices)`)
} else {
  process.stdout.write(source)
}
